name: Create pull request to master from testing.
on:
  push:
    branches:
      - testing
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: testing
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: master
          commit-message: "Pull request testing-->master (M.P)"
